# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16fb127028bd64fa6d30e81bd24e2506292348dfab7043ee7ffdb64fba16cd84536aa6ba32cd3f9882df73e0479756f08920ce1b38a3eae93e9b69890cf41f8

test:
  secret_key_base: b50b1aa433aed2c3360047885ed5385aff2f6755e4cb8d3d89b5ad31dc15766e8139c0830625c9c3b5128592319aa2cabb4f791088dc0dc3a101f3fd421ca80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
